### ISSUE TITLE
0.0.0.0 accepted host does not accept all hosts.

### ISSUE THREAD

**Issue by wwitzel3** [vmware/octant#199]
The expected behavior would be that since `0.0.0.0` is allowed any `request.Host` would be allowed. `0.0.0.0` is common short hand for "all hosts in IPv4"

related #152 #188 #173

**Comment by GuessWhoSamFoo** [comment]
Worked through a few cases using ngrok as an example where failures result in 403 seen in #188

1) Rewrite host header to octant's address when tunneling requests

Run octant on `localhost:7777` then set host header with the proxy `ngrok http 7777 -host-header="localhost:7777"`

2) Set the accepted host with octant

Start `ngrok http 7777`. Get the forwarding address then `OCTANT_ACCEPTED_HOSTS=2d2455ba.ngrok.io octant`

3) (Fixed in #200 ) Set listening on 0.0.0.0:7777 which will allow all hosts

Start `ngrok http 7777`. Run `OCTANT_LISTENER_ADDR=0.0.0.0:7777 octant`
